UPSTREAM: obexd: Fix compilation error on newer glibc
Since this glibc commit:
https://sourceware.org/git/gitweb.cgi?p=glibc.git;a=commitdiff;h=37f802f86400684c8d13403958b2c598721d6360

glibc doesn't include declare ssize_t when fcntl.h is included (fcntl.h
included <bits/uio.h> which includes <sys/types.h>).

This fixes the following compile-time error:

In file included from obexd/plugins/mas.c:41:0:
./obexd/src/obex.h:37:1: error: unknown type name ssize_t; did you mean size_t?
 ssize_t obex_get_size(struct obex_session *os);
 ^~~~~~~

BUG=chromium:862240
TEST=emerge-samus bluez with glibc 2.27

Change-Id: Ie89ca437f6f831eea632c857876011a5e39188bc
Reviewed-on: https://chromium-review.googlesource.com/1131825
Commit-Ready: Yunlian Jiang <yunlian@chromium.org>
Tested-by: Yunlian Jiang <yunlian@chromium.org>
Reviewed-by: Miao-chen Chou <mcchou@chromium.org>
Reviewed-by: Qiyu Hu <qiyuh@google.com>