UPSTREAM: build: Fix build with latest ELL tree
Latest ELL tree has introduced useful.h and main-private.h which are
required to build:

ell/cert-crypto.c:35:10: fatal error: useful.h: No such file or
directory
   35 | #include "useful.h"
         |          ^~~~~~~~~~
...

(cherry picked from commit 571e41a19a25f527daad2911f0b4e76a640d6ef4)

BUG=none
TEST=none

Change-Id: I6888ee33d7640e7eb086823c2ed7ca14968e0f58
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/bluez/+/3186124
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Reviewed-by: Alain Michaud <alainm@chromium.org>
Tested-by: Archie Pusaka <apusaka@chromium.org>
Commit-Queue: Archie Pusaka <apusaka@chromium.org>